#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
#    Copyright (C) 2025
#    Simón Villanueva CORRALES: simon.corrales@ibot.cas.cz
#    Yann J.K. BERTRAND: yjk_bertrand@ybertrand.org
#
#       All rights reserved.
"""
Functions and classes for running miniprot in different steps of the pipeline

The class OverlappingCds is used after the vsearch clustering of SAUTE scaffolds and consensus estimation.
It maps all probe versions against the consensus sequences of vsearch clusters. It seeks
to find the best mapping probe version over all the consensus sequences and use it as
a common reference in order to determine which sequences are not overlapping.
Strictly non-overlapping sequences (there are no bridging scaffolds) are saved in separate
files.
Exon-intron boundaries are then inferred with miniprot-boundary-scored (https://anaconda.org/bioconda/miniprot-boundary-scorer)
that rely on a AA substitution matrix. The most common boundaries are used to discriminate scaffolds that do not
present these boundaries. These scaffolds are treated as paralogs.
#  Usage example:
    probe_fasta = ".../test_data/test_clustering/probe_3_aa.fasta"
    consensus_contig_fasta = "../test_data/test_clustering/gene_3_consensus.fasta"
    # load the data, perform the computation in order to separate non-overlapping sequences:
    olc = OverlappingCds(probe_fasta, consensus_contig_fasta)
    # perform paralogy search
    matrix = "../test_data/test_paralogy_2/blosum62.csv"
    olc.paralogy_search(matrix)
    # specify a folder where each non-overlapping group of sequences is saved in fasta format.
    # For each group, putative aligned exons and introns sequences are produced as well as unaligned supercontigs.
    # Putative paralogs are saved in a separate file.
    olc.save_records("../test_data/test_clustering/non_overlapping/")
    # save the sequence of the best overall mapping probe.
    olc.save_best_probe("../test_data/test_clustering/gene_3_best_probe.fasta")
"""

__version__ = "0.1"

# =======================================================================================
#               IMPORTS
# =======================================================================================

from dataclasses import dataclass, field
from collections import defaultdict, namedtuple, deque
from importlib import reload
from io import StringIO
from itertools import chain
from operator import attrgetter
from pathlib import Path
import subprocess
import sys
import tempfile
import textwrap
from typing import Optional, Self, NamedTuple

from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
from Bio.Seq import Seq
from intervaltree import Interval
import pyabpoa as pa

from exon_discovery import DiscoverExons
from gff_parser import Fragment, Cds

# from interval_tree import Node
from exon_intron import ItervalGraph, GraphPath, Exon

Region = namedtuple("Region", ["start", "end"])


# =======================================================================================
#               FUNCTIONS
# =======================================================================================


def merge_intervals(arr: list["OverlappingSeqs"]) -> list["OverlappingSeqs"]:
    """
    Combine overlapping intervals of sequences and cluster their names.
    We can thus separate the group of sequences according to non-overlapping intervals.
    """
    # Sorting based on the increasing order of the start intervals
    arr.sort(key=attrgetter("probe_start"))
    index = 0
    index_to_del = []
    for i in range(1, len(arr)):
        if arr[index].probe_end > arr[i].probe_start:
            arr[index].probe_end = max(arr[index].probe_end, arr[i].probe_end)
            arr[index].combine(arr[i].seq_names)
            index_to_del.append(i)
        else:
            index = index + 1
            arr[index] = arr[i]
    return [arr[index] for index in range(len(arr)) if index not in index_to_del]


def remove_gff(miniprot_out) -> bytes:
    """
    Transform a PAF file generated by 'miniprot --gff --aln' that is used to create Cds objects,
    into a file that would be obtained with the option 'miniprot --aln' that can be used as
    input for 'miniprot --gff --aln'.
    """
    new_lines = []
    for line in miniprot_out:
        if line.startswith("##PAF"):
            new_lines.append(line.replace("##PAF	", ""))
        if (
            line.startswith("##ATN")
            or line.startswith("##ATA")
            or line.startswith("##AAS")
            or line.startswith("##AQA")
        ):
            new_lines.append(line)
    return "".join(new_lines).encode()


def run_miniprot(
    probe_path: Path,
    contig_path: Path,
    treads=2,
    min_similarity=0.85,
    min_coverage=0.01,
) -> StringIO | str:
    """
    Wrapper for running miniprot.
    :return:
    """
    miniprot_cmd = f"miniprot -t {treads} --gff --aln --outn 1 -J 50 --outs {min_similarity} --outc {min_coverage} {contig_path} {probe_path}".split()
    try:
        miniprot = subprocess.run(
            miniprot_cmd,
            timeout=1000,
            check=True,
            capture_output=True,
            encoding="utf-8",
        )
    except FileNotFoundError as exc:
        print(f"Process failed because the executable could not be found.\n{exc}")
        raise
    except subprocess.CalledProcessError as exc:
        print(
            f"Process failed because did not return a successful return code. "
            f"Returned {exc.returncode}\n{exc}"
        )
        raise
    except subprocess.TimeoutExpired as exc:
        print(f"Process timed out.\n{exc}")
        raise
    return StringIO(miniprot.stdout)


def run_miniprot_boundary_scorer(
    miniprot: bytes, boundary_scorer_out: Path, matrix_path: Path
):
    """
    Wrapper for running miniprot_boundary_scorer.
    :return:
    """
    boundary_scorer_cmd = (
        f"miniprot_boundary_scorer -o {boundary_scorer_out} -s {matrix_path}"
    )
    try:
        subprocess.run(
            boundary_scorer_cmd,
            timeout=10,
            shell=True,
            input=miniprot,
        )
    except FileNotFoundError as exc:
        print(f"Process failed because the executable could not be found.\n{exc}")
        raise
    except subprocess.CalledProcessError as exc:
        print(
            f"Process failed because did not return a successful return code. "
            f"Returned {exc.returncode}\n{exc}"
        )
        raise
    except subprocess.TimeoutExpired as exc:
        print(f"Process timed out.\n{exc}")
        raise


# =======================================================================================
#               CLASSES
# =======================================================================================


@dataclass
class RankCoverage:
    """
    Container for keeping track of the rank of a given probe out of all probes ranks.
    Attributes
    ----------
    -rank_score: list of ranks. Each int represents how a well given probe aligns to a scaffolds
        compared to the other probes. Smaller ranks denote better mapping.
    -coverage: list of scaffolds to which this probe aligns.
    """

    rank_score: list[int] = field(default_factory=list)
    coverage: list[str] = field(default_factory=list)

    def append_to(self, item_0, item_1):
        self.rank_score.append(item_0)
        self.coverage.append(item_1)

    def get_mean_score(self, nbr_contigs: int):
        """The  score used for the global ranking is based on probe positions, the total number of
        scaffolds and the scaffolds without a match. Missing matches get a penalty equal to the maximum rank,
         e.g. rank_score=[0, 3, 1, 0], coverage=['contig_0', 'contig_1', 'contig_2', 'contig_3']
         and nbr_contigs=6  produces a score of (4+6+6)/6"""
        missing_contigs = nbr_contigs - len(self.coverage)
        missing_scores = [nbr_contigs for _ in range(missing_contigs)]
        return (sum(self.rank_score) + sum(missing_scores)) / nbr_contigs


@dataclass
class Exon_correspondence:
    """
    Probe to scaffold coordinates
    Attributes
    ----------
    exon_probe: start-end coordinates on the probe.
    exon_scaffold: start-end coordinates on the scaffold.
    length_on_scaffold: nbr of AAs that are aligned between the probe and the scaffold.
    """

    __slots__ = ["exon_probe", "exon_scaffold", "length_on_scaffold"]
    exon_probe: Exon
    exon_scaffold: Exon
    length_on_scaffold: int

    def check_compatibility(self, other: Exon, sensitivity: int) -> bool:
        """
        Given another probe exon coordinates, check if this exon is compatible:
        whether it is the same set of coordinates or whether this exon comes from
        the fusion of two exons and the query is one of them. Currently, only takes into account the fusion of two exons.
        Parameters
        ----------
        other
        sensitivity: the range around the query coordinates that should be searched for a match.

        Returns bool
        -------

        """
        probe_start = self.exon_probe.start
        probe_end = self.exon_probe.end
        other_probe_start = other.start
        other_probe_end = other.end
        print(f"{probe_start=},{probe_end=},{other_probe_start=},{other_probe_end=}")
        if self.exon_probe == other:
            return True
        # case the other exon is made out of the fusion of two exons. This probe exon is the left part of the other exon.
        if (
            probe_start - sensitivity <= other_probe_start <= probe_start + sensitivity
        ) and (other_probe_end - sensitivity <= probe_end):
            return True
        # case the other exon is made out of the fusion of two exons. This probe exon is the right part of the other exon.
        if (probe_start <= other_probe_start + sensitivity) and (
            probe_end - sensitivity <= other_probe_end <= probe_end + sensitivity
        ):
            return True
        return False


@dataclass
class Boundary:
    """
    coordinate on scaffold
    """

    __slots__ = ["scaffold_name", "scaffold_start", "scaffold_end"]
    scaffold_name: str
    scaffold_start: int
    scaffold_end: int


@dataclass
class ParalogyCds(Cds):
    """
    Cds object with additional features to handle paralogy information
    correspondence scaffold coordinates to probe coordinates
    rev_correspondence probe coordinates to scaffold coordinates
    exon_correspondences: Exon_correspondence(exon_probe=Exon(start=71, end=110), exon_scaffold=Exon(start=17, end=132), length_on_scaffold=115)
    """

    exon_probe_scaffold: list = field(init=False, default_factory=list)
    correspondence: dict[int, int] = field(default_factory=dict, init=False, repr=True)
    rev_correspondence: dict[int, int] = field(
        default_factory=dict, init=False, repr=True
    )
    exon_correspondences: list[Exon_correspondence] = field(
        default_factory=list, init=False, repr=True
    )
    accepted_exons: list[Exon] = field(default_factory=list, init=False, repr=True)

    def __post_init__(self):
        super().__post_init__()
        self._reverse_correspondence()

    def _reverse_correspondence(self) -> Self:
        """
        Populate the correspondence, rev_correspondence, start_on_probe and end_on_probe attributes.
        """
        for fragment in self.fragments:
            for k, v in fragment.correspondence.items():
                self.correspondence[k] = v
                self.rev_correspondence[v] = k
        self.start_on_probe = min(self.rev_correspondence)
        self.end_on_probe = max(self.rev_correspondence)
        return self

    def find_probe_exons(self, exons: list[Exon]) -> Self:
        """
        Find coordinates pairs on the probe where exons are located
        """
        for scaff_exon in exons:
            probe_start = None
            probe_end = None
            for idx in [0, 1, 2, -1, -2]:
                if (
                    probe_start := self.rev_correspondence.get(scaff_exon.start + idx)
                ) is not None:
                    break
            for idx in [0, 1, 2, -1, -2]:
                if (
                    probe_end := self.rev_correspondence.get(scaff_exon.end + idx)
                ) is not None:
                    break
            if None not in [probe_start, probe_end]:
                probe_exon = Exon(probe_start, probe_end)
                length = scaff_exon.end - scaff_exon.start
                self.exon_correspondences.append(
                    Exon_correspondence(probe_exon, scaff_exon, length)
                )
        return self


@dataclass
class OverlappingSeqs:
    """
    Container for groups of sequences that overlap a common region of the probe.
    Attributes
    ----------
    -probe_start: the smallest index on the probe (AA space) that has a matching sequence.
    -probe_end: the largest index on the probe (AA space) that has a matching sequence.
    -seq_names: a list of sequence names that overlap this region.
    -cds_dict
    -common_exons: exons found in a majority of scaffolds
    -paralogs: list of scaffolds that are deemed to be paralogs.
    To do: in the final paralog selection add the sequences that are present in OverlappingCds.cds_dict
    but disappear in filtered_cds_dict.
    -scaffold_exons: for each exon region keep a list of scaffold Boundaries that correspond to this exon.
    -scaffold_introns: for each intron region keep a list of scaffold Boundaries that correspond to this intron.
    """

    probe_start: int
    probe_end: int
    seq_names: list[str]
    cds_dict: dict[str, ParalogyCds] = field(
        init=False, repr=False, default_factory=dict
    )
    common_exons: list[Exon] = field(init=False, repr=False, default_factory=list)
    paralogs: list[str] = field(init=False, repr=False, default_factory=list)
    scaffold_exons: defaultdict[Region, list[Boundary]] = field(
        default_factory=lambda: defaultdict(list)
    )
    scaffold_introns: defaultdict[int, list[Boundary]] = field(
        default_factory=lambda: defaultdict(list)
    )

    def find_common_exons(
        self,
        min_overlapping=0.0,
    ):
        """
        min_proportion: minimum proportion of samples (that have a probe match) that have the exon.
            If a scaffold is too short, it is counted in the proportion anyway.
        to do: check cases when the exon path is discontinuous.
        """
        #  Find the non overlapping exon regions
        print("finding common exons")
        exon_intervals = []
        for contig in self.cds_dict:
            cds = self.cds_dict[contig]
            if cds.is_empty():
                continue
            for exon_pair in cds.exon_correspondences:
                exon_intervals.append(
                    Interval(
                        exon_pair.exon_probe.start, exon_pair.exon_probe.end, contig
                    )
                )
        print(f"exon_intervals: {exon_intervals}")
        exon_discovery = DiscoverExons(exon_intervals, min_overlapping)
        self.common_exons = exon_discovery.get_exons()
        print("common exons", self.common_exons)

    def eliminate_paralogs(self, overlap: int):
        """
        A paralog is defined as a contig missing an exon surrounded by common_exons
        """

        if not self.common_exons:
            print("no valid exon")
            # add all sequences to paralogs
            self.paralogs.extend(self.cds_dict)
            return

        for scaffold, cds in self.cds_dict.items():
            print(f"working on {scaffold}")
            presence_of_probe_exon: list[bool] = (
                []
            )  # keep track of the presence of the valid exons in the scaffold
            probe_exon_to_scaffold_dict: dict[Region, Exon] = {}
            valid_exons = deque(self.common_exons)
            correspondences = deque(cds.exon_correspondences)

            def is_compatible(
                query_exon: Exon_correspondence,
                probe_exon: Node,
                first_exon_probe: bool,
                last_exon_probe: bool,
            ) -> bool:
                """
                Find if two probe intervals are compatible.
                One set of non-overlapping most common intervals constitute the probe_exon.
                The scaffold exon is queried against the probe_exon.
                Flanking intervals of the query are treated differently.
                A special case applies when there is a putative fused interval on the scaffold.
                :param query_exon: the Exon_correspondence object under scrutiny.
                :param probe_exon: an interval_tree Node object containing as attributes, an Interval object and a value
                    that reports the name of all the contigs that display this exon.
                :param first_exon_probe: if the probe_exon is the first on the exon path.
                :param last_exon_probe: if the probe_exon is the last on the exon path.
                """
                query_start, query_end = (
                    query_exon.exon_probe.start,
                    query_exon.exon_probe.end,
                )
                probe_start = probe_exon.interval.lo
                probe_end = probe_exon.interval.hi
                # Cases we deal with the flanking exons, which can vary in size.
                if first_exon_probe:
                    if (
                        query_start < probe_end
                        and max(0, query_end - overlap)
                        <= probe_end
                        <= query_end + overlap
                    ):
                        # print("case 1")
                        probe_exon_to_scaffold_dict[Region(probe_start, probe_end)] = (
                            query_exon.exon_scaffold
                        )
                        return True
                if last_exon_probe:
                    if (
                        max(0, query_start - overlap)
                        <= probe_start
                        <= query_start + overlap
                    ) and query_end > probe_start:
                        # print("case 2")
                        probe_exon_to_scaffold_dict[Region(probe_start, probe_end)] = (
                            query_exon.exon_scaffold
                        )
                        return True
                # Case with regular exon
                if (
                    max(0, query_start - overlap)
                    <= probe_start
                    <= query_start + overlap
                ) and (max(0, query_end - overlap) <= probe_end <= query_end + overlap):
                    # print("case 3")
                    probe_exon_to_scaffold_dict[Region(probe_start, probe_end)] = (
                        query_exon.exon_scaffold
                    )
                    return True
                # Cases including fused exons
                if (
                    max(0, query_start - overlap)
                    <= probe_start
                    <= query_start + overlap
                ) and query_end > probe_end:
                    print("fused exon case")
                    # to do check that the rev_correspondence works in all cases
                    new_exon_probe_start = probe_end
                    new_exon_probe_end = query_end
                    new_exon_scaffold_start = cds.rev_correspondence[probe_end] + 1
                    new_exon_scaffold_end = query_exon.exon_scaffold.end
                    new_length_on_scaffold = (
                        new_exon_scaffold_end - new_exon_scaffold_start
                    )
                    new_exon_correspondence = Exon_correspondence(
                        Exon(new_exon_probe_start, new_exon_probe_end),
                        Exon(new_exon_scaffold_start, new_exon_scaffold_end),
                        new_length_on_scaffold,
                    )
                    correspondences.appendleft(new_exon_correspondence)
                    new_scaffold_exon = Exon(
                        query_exon.exon_scaffold.start,
                        cds.rev_correspondence[probe_end],
                    )
                    probe_exon_to_scaffold_dict[Region(probe_start, probe_end)] = (
                        new_scaffold_exon
                    )
                    sys.exit("case4")
                    return True
                # print("case 5")
                return False

            # go through all the probe exons
            first_exon_probe = True
            while valid_exons:
                if not correspondences:
                    #  pad the rest of the array with False
                    presence_of_probe_exon.extend(
                        [
                            False
                            for _ in range(
                                len(self.common_exons) - len(presence_of_probe_exon)
                            )
                        ]
                    )
                    break
                probe_exon = valid_exons.popleft()

                # search the probe exons in the scaffold exons
                while correspondences:
                    scaffold_exon = correspondences.popleft()
                    # print(f"checking scaffold {scaffold_exon}")
                    if not correspondences:
                        last_exon_probe = True
                    else:
                        last_exon_probe = False
                    compatibility = is_compatible(
                        scaffold_exon,
                        probe_exon,
                        first_exon_probe,
                        last_exon_probe,
                    )
                    first_exon_probe = False
                    if compatibility:
                        # Continue with the next probe and scaffold intervals.
                        presence_of_probe_exon.append(True)
                        break
                    if not correspondences:
                        #  All scaffolds intervals have been checked, reset the search.
                        presence_of_probe_exon.append(False)
                        first_exon_probe = True
                        correspondences = deque(cds.exon_correspondences)
                        break
                    continue
            # print(f"{presence_of_probe_exon}\n")
            # Check if a missing exon is surrounded by two identified exons
            ortholog = True
            if set(presence_of_probe_exon) == {False}:
                ortholog = False
            elif set(presence_of_probe_exon) == {True}:
                pass
            else:
                flag_true = False
                flag_false = False
                target_idx = presence_of_probe_exon[0]
                queue = presence_of_probe_exon[1:]
                while queue:
                    if target_idx == True:
                        if flag_true and flag_false:
                            ortholog = False
                            break
                        flag_true = True
                    elif target_idx == False:
                        if flag_true:
                            flag_false = True
                    target_idx = queue[0]
                    queue = queue[1:]

            if ortholog:
                for region, exon in probe_exon_to_scaffold_dict.items():
                    boundary = Boundary(scaffold, exon.start, exon.end)
                    self.scaffold_exons[region].append(boundary)
            else:
                self.paralogs.extend(scaffold)

        print("exons:", list(self.scaffold_exons.items()))
        self.compute_introns()
        print("introns", list(self.scaffold_introns.items()))

    def compute_introns(self):
        """
        Once orthologs have been identified, we can focus on intron, defined as region bounded
        by exons
        """
        if self.scaffold_exons and len(self.common_exons) > 1:
            for idx in range(len(self.scaffold_exons) - 1):
                first_region = list(self.scaffold_exons.keys())[idx]
                second_region = list(self.scaffold_exons.keys())[idx + 1]
                for first_boundary in self.scaffold_exons[first_region]:
                    for second_boundary in self.scaffold_exons[second_region]:
                        if (
                            first_boundary.scaffold_name
                            == second_boundary.scaffold_name
                        ):
                            break
                    else:
                        continue
                    intron_boundary = Boundary(
                        first_boundary.scaffold_name,
                        first_boundary.scaffold_end,
                        second_boundary.scaffold_start,
                    )
                    self.scaffold_introns[idx].append(intron_boundary)

    def combine(self, other: list[str]) -> Self:
        """
        Add items to seq_names
        """
        self.seq_names.extend(other)
        return self

    def __repr__(self):
        return (
            f"probe_start={self.probe_start}, probe_end={self.probe_end},"
            f"{sorted(self.seq_names)}"
        )


@dataclass
class MiniprotInit:
    """
    Base class for miniprot initialization.
    Attributes
    ----------
    -probes_fasta: path to the amino acid probes fasta file (multiprobe)
    -contigs_fasta: path to the nucleotide contigs fasta file.
    -treads: for miniprot.
    -min_probe_contig_sim: mapping similarity for miniprot.
    -min_fragment_cov: fraction of the probe covered by a contig for miniprot.
    -min_contig_length: minimum length of a contig after trimming, if the sequences are saved.
    -min_global_identity: identity over all several fragments. Should be slightly lower than min_probe_contig_sim.

    Post Init
    -probes_path: probe_fasta string converted to Path.
    -contigs_path: contigs_fasta string converted to Path.
    -probes_dict: dict of probe name as key and SeqRecord as value.
    -contigs_dict: dict of contig name as key and SeqRecord as value.

    """

    probes_fasta: str
    contigs_fasta: str
    treads: int = field(default=8)
    min_probe_contig_sim: float = field(default=0.85)
    min_fragment_cov: float = field(default=0.05)
    min_contig_length: int = field(default=300)
    min_global_identity: float = field(default=0.00)
    probes_path: Path = field(init=False, repr=False)
    contigs_path: Path = field(init=False, repr=False)
    probes_dict: dict[str, SeqRecord] = field(
        init=False, repr=False, default_factory=dict
    )
    contigs_dict: dict[str, SeqRecord] = field(
        init=False, repr=False, default_factory=dict
    )

    def __post_init__(self):
        self.probes_path = Path(self.probes_fasta)
        self.contigs_path = Path(self.contigs_fasta)
        assert self.probes_path.exists(), f"{self.probes_fasta} does not exist"
        assert self.contigs_path.exists(), f"{self.contigs_fasta} does not exist"
        self._parse_fasta()

    def _parse_fasta(self) -> None:
        """
        Load the probe fasta file and the contig fasta file.
        :return:
        """
        try:
            self.probes_dict = SeqIO.to_dict(SeqIO.parse(self.probes_path, "fasta"))
        except Exception as err:
            sys.exit(f"[ERROR] {err}")
        try:
            self.contigs_dict = SeqIO.to_dict(SeqIO.parse(self.contigs_path, "fasta"))
        except Exception as err:
            sys.exit(f"[ERROR] {err}")

    def _run_miniprot(
        self, record, probe_path_temp, contig_path_temp, paralogy=False
    ) -> Cds:
        SeqIO.write(record, contig_path_temp, "fasta")
        miniprot_out = run_miniprot(
            probe_path_temp,
            contig_path_temp,
            self.treads,
            self.min_probe_contig_sim,
            self.min_fragment_cov,
        )
        if paralogy:
            return miniprot_out
        return Cds(miniprot_out)


@dataclass
class OverlappingCds(MiniprotInit):
    """
    Data structure for selecting the best probe over the entire set of scaffolds.
    The probe is then used as reference for separating non overlapping scaffolds.
    Attributes
    ----------
    Post Init
    -cds_dict: dict of contig name as key and list of Cds object as value.
    -filtered_cds_dict: dict of contig name as key and the Cds that corresponds to the best overall probe,
        discarding sequences without matches
    -non_overlapping: list of OverlappingSeqs objects that keep track of overlapping sequences and position on probe.
    -best_probe: name of the probe version that has the overall best mapping score.
    """

    user_probe: str = field(default=None)
    min_overlapping = 0.1
    cds_dict: defaultdict[str, list[Cds]] = field(
        init=False, repr=False, default_factory=lambda: defaultdict(list)
    )
    filtered_cds_dict: dict[str, Cds] = field(
        init=False, repr=False, default_factory=dict
    )
    non_overlapping: list[OverlappingSeqs] = field(init=False, default_factory=list)
    best_probe: str = field(init=False, default=None)

    def __post_init__(self):
        super().__post_init__()
        # run miniprot on each scaffold/probe combination
        print(f"{self.user_probe=}")
        with tempfile.TemporaryDirectory() as tmpdirname:
            tmp_probe_paths = {}
            # write all probe records in separate file
            if (
                self.user_probe is not None
                and self.user_probe in self.probes_dict.keys()
            ):
                print(f"User selected probe is {self.user_probe}")
                fasta_name = f"{self.user_probe}.fas"
                contig_fasta = Path(tmpdirname) / fasta_name
                SeqIO.write(self.probes_dict[self.user_probe], contig_fasta, "fasta")
                tmp_probe_paths[self.user_probe] = contig_fasta

            else:
                print("creating probe list")
                for probe_name, record in list(self.probes_dict.items())[:]:
                    fasta_name = f"{probe_name}.fas"
                    contig_fasta = Path(tmpdirname) / fasta_name
                    SeqIO.write(record, contig_fasta, "fasta")
                    tmp_probe_paths[probe_name] = contig_fasta
            for contig, record in self.contigs_dict.items():
                print(f"working on contig {contig}")
                for probe_name, probe_path in tmp_probe_paths.items():
                    print(f"working on probe {probe_name}")
                    fasta_name = f"{contig}.fas"
                    contig_path = Path(tmpdirname) / fasta_name
                    cds = self._run_miniprot(record, probe_path, contig_path)
                    cds.probe_name = probe_name
                    if (
                        not cds.is_empty()
                        and cds.global_identity >= self.min_global_identity
                    ):
                        self.cds_dict[contig].append(cds)
                print("cds", self.cds_dict.get(contig))
            print("computing rank score")
            self._compute_rank_score()
            print("initial sequences:", len(self.cds_dict))
            print("filtered sequences:", len(self.filtered_cds_dict))
            print("sorting overlapping")
            self._sorting_overlapping()
            print("done sorting overlapping")
            # print("non_overlapping", self.non_overlapping)

    def _compute_rank_score(self) -> Self:
        """
        Find the probe that has the best overall match using the miniprot score.
        Populate the 'best_probe' attribute.
        """
        if not self.cds_dict.values():
            return self
        probe_ranks = defaultdict(RankCoverage)  # score per contig
        for contig, list_cds in self.cds_dict.items():
            probe_scores = sorted(
                [(cds.probe_name, cds.get_global_score()) for cds in list_cds],
                key=lambda x: x[1],
                reverse=True,
            )
            for idx, probe_score in enumerate(probe_scores):
                probe_name = probe_score[0]
                probe_ranks[probe_name].append_to(idx, contig)

        best_combination = sorted(
            probe_ranks.items(), key=lambda x: x[1].get_mean_score(len(self.cds_dict))
        )[0]

        self.best_probe = best_combination[0]
        print(f"Best overall probe: {self.best_probe}")
        # Keep only contigs that are covered by the best probe
        for contig in best_combination[1].coverage:
            self.filtered_cds_dict[contig] = [
                cds
                for cds in self.cds_dict[contig]
                if cds.probe_name == self.best_probe
            ][0]
        return self

    def _sorting_overlapping(self) -> Self:
        """
        Separate the Cds by overlap with the probe sequence.
        Populate the non_overlapping attribute
        """
        interval_list = []
        for contig, cds in self.filtered_cds_dict.items():
            print(f"{contig=}, {cds=}")
            if cds.is_empty():
                continue
            start = cds.probe_start
            end = cds.probe_end
            interval_list.append(OverlappingSeqs(start, end, [contig]))
        self.non_overlapping = merge_intervals(interval_list)
        return self

    def _boundary_scorer_parser(self, boundary_scorer_path: Path) -> list[Exon]:
        """
        Parser of the miniprot_boundary_scorer output.
        Create for each record a list of Exon objects.
        """
        lines = boundary_scorer_path.read_text().split("\n")
        exons = []
        for line in lines:
            if not line:
                continue
            splt = line.split("\t")
            if splt[2] == "CDS" and splt[6] == "+":
                exons.append(Exon(int(splt[3]) - 1, int(splt[4]) - 3))
        return exons

    def paralogy_search(self, substitution_matrix: Path):
        """
        On each OverlappingSeqs object perform a matching exon search.
        The output of miniprot is converted into a format that run_miniprot_boundary_scorer can parse.

        """
        if not self.non_overlapping:
            print("No overlapping group")
            return
        with tempfile.TemporaryDirectory() as tmpdirname:
            probe_record = self.probes_dict[self.best_probe]
            probe_name = f"{self.best_probe}.fas"
            probe_path = Path(tmpdirname) / probe_name
            SeqIO.write(probe_record, probe_path, "fasta")

            for overlapping_gp in self.non_overlapping:
                #  Run miniprot on each contig on each group of overlapping sequences
                for contig in overlapping_gp.seq_names:
                    record = self.contigs_dict[contig]
                    contig_path = Path(tmpdirname) / f"{contig}.fas"
                    miniprot_out = self._run_miniprot(
                        record, probe_path, contig_path, paralogy=True
                    )
                    cds = ParalogyCds(miniprot_out)
                    cds.length = len(SeqIO.read(contig_path, "fasta").seq)
                    miniprot_out.seek(0)
                    boundary_scorer_out = (
                        Path(tmpdirname) / f"{contig_path.stem}_boundary.gfa"
                    )
                    # run miniprot_boundary scorer
                    run_miniprot_boundary_scorer(
                        remove_gff(miniprot_out),
                        boundary_scorer_out,
                        substitution_matrix,
                    )
                    # use boundary scorer to define the exon/intron boundaries
                    cds.find_probe_exons(
                        self._boundary_scorer_parser(boundary_scorer_out)
                    )
                    overlapping_gp.cds_dict[contig] = cds
                overlapping_gp.find_common_exons(self.min_overlapping)
                print("eliminate paralogs")
                overlapping_gp.eliminate_paralogs(5)

    def save_records(self, outdir: Path):
        stem_name = self.probes_path.stem
        print(f"saving {stem_name}")

        for overlapping_gp in self.non_overlapping:
            prefix = (
                f"{stem_name}_{overlapping_gp.probe_start}_{overlapping_gp.probe_end:}"
            )

            if overlapping_gp.scaffold_exons:
                #  Save exons
                name = f"{prefix}_exons.fasta"
                out_path_exon = outdir / name
                aligned_records: list[list[SeqRecord]] = []
                for exon, boundaries in overlapping_gp.scaffold_exons.items():
                    records = []
                    # Adjusting the exon boundaries according in order to match the most common exon
                    for boundary in boundaries:
                        scaffold_name = boundary.scaffold_name
                        paralogy_cds = overlapping_gp.cds_dict[scaffold_name]
                        if (
                            start := paralogy_cds.correspondence.get(exon.start)
                        ) is not None:
                            pass
                        else:
                            start = boundary.scaffold_start
                        if (
                            end := paralogy_cds.correspondence.get(exon.end)
                        ) is not None:
                            pass
                        else:
                            end = boundary.scaffold_end
                        chopped_seq = str(self.contigs_dict[scaffold_name].seq)[
                            start:end
                        ]
                        records.append(
                            SeqRecord(
                                Seq(chopped_seq),
                                name="",
                                description="",
                                id=scaffold_name,
                            )
                        )
                    aligned_records.append(_align_abpoa(records))
                combined_records = _combine_aln(aligned_records)
                SeqIO.write(combined_records, out_path_exon, "fasta")
                #  Save supercontigs
                super_name = f"{prefix}_supercontigs.fasta"
                out_path_supercontigs = outdir / super_name
                super_records = [self.contigs_dict[rec.id] for rec in combined_records]
                SeqIO.write(super_records, out_path_supercontigs, "fasta")

            if overlapping_gp.scaffold_introns:
                name = f"{prefix}_intron.fasta"
                out_path_intron = outdir / name
                aligned_records: list[list[SeqRecord]] = []
                for intron, boundaries in overlapping_gp.scaffold_introns.items():
                    records = []
                    for boundary in boundaries:
                        scaffold_name = boundary.scaffold_name
                        start = boundary.scaffold_start
                        end = boundary.scaffold_end
                        chopped_seq = str(self.contigs_dict[scaffold_name].seq)[
                            start:end
                        ]
                        records.append(
                            SeqRecord(
                                Seq(chopped_seq),
                                name="",
                                description="",
                                id=scaffold_name,
                            )
                        )
                    aligned_records.append(_align_abpoa(records))
                combined_records = _combine_aln(aligned_records)
                SeqIO.write(combined_records, out_path_intron, "fasta")

            if overlapping_gp.paralogs:
                paralog_records = [
                    self.contigs_dict[para] for para in overlapping_gp.paralogs
                ]
                name = f"{prefix}_paralogs.fasta"
                out_path_paralogs = outdir / name
                SeqIO.write(paralog_records, out_path_paralogs, "fasta")

    def save_best_probe(self, fasta_path: Path) -> None:
        fasta_path.parent.mkdir(parents=True, exist_ok=True)
        print(f"Saving best probe to fasta file {fasta_path}")
        SeqIO.write([self.probes_dict[self.best_probe]], fasta_path, "fasta")


def _align_abpoa(records: list[SeqRecord]) -> list[SeqRecord]:
    print("aligning")
    new_records = []
    a = pa.msa_aligner(is_aa=False)
    seqs = [str(rec.seq) for rec in records]
    res = a.msa(seqs, out_cons=False, out_msa=True)
    for idx, rec in enumerate(records):
        new_records.append(
            SeqRecord(Seq(res.msa_seq[idx]), id=rec.id, name="", description="")
        )
    return new_records


def _combine_aln(alignments: list[list[SeqRecord]]) -> list[SeqRecord]:
    """Combine several msa, for instance when several exons need to be combined.
    Missing sequences are padded with '-'"""
    msa_dicts = []
    msa_length = []
    for msa in alignments:
        msa_length.append(len(msa[0].seq))
        msa_dicts.append({rec.id: str(rec.seq) for rec in msa})
    rec_ids = set(list(chain(*[d.keys() for d in msa_dicts])))
    new_records = []
    for rec_id in rec_ids:
        seq = ""
        for idx, msa_dict in enumerate(msa_dicts):
            if rec_id in msa_dict:
                seq += msa_dict[rec_id]
            else:
                seq += "-" * msa_length[idx]
        new_records.append(SeqRecord(Seq(seq), id=rec_id, name="", description=""))
    return new_records


def snakemake_call(snakemake):
    with open(snakemake.log[0], "w") as outlog:
        sys.stdout = sys.stderr = outlog

        outdir = Path(snakemake.output[0])
        outdir.mkdir(exist_ok=True)
        probes_dir = Path(snakemake.input.probes_dir)

        for scfs in Path(snakemake.input.scfs_dir).glob("*.fasta"):
            probes = probes_dir / scfs.name
            olc = OverlappingCds(probes, scfs, **snakemake.params)

            if not olc.non_overlapping:
                print(f"Scaffolds from {probes.stem} did not yield any overlap")
                (outdir / "scfs" / scfs.stem).touch(exist_ok=True)
                continue

                ## Save scfs
            olc.save_scaffolds(outdir / "scfs" / scfs.stem)

            ## Save Probes
            olc.save_best_probe(outdir / f"probes/{probes.name}")


def main():
    # probe_dir = Path(
    #     '/home/yjkbertrand/Documents/projects/nextpiper/debug/NextPyper_hieracium/Merged_run/First_rna_targeted/results_full2/aster_kew_rna/homolog_prospection/region_separation/input_probes')
    # scaffolds_dir = Path(
    #     '/home/yjkbertrand/Documents/projects/nextpiper/debug/NextPyper_hieracium/Merged_run/First_rna_targeted/results_full2/aster_kew_rna/homolog_prospection/region_separation/input_scfs')
    # out_dir = Path(
    #     '/home/yjkbertrand/Documents/projects/nextpiper/debug/NextPyper_hieracium/Merged_run/First_rna_targeted/results_full2/aster_kew_rna/homolog_prospection/region_separation/output_scfs')
    probe_dir = Path(
        "/home/yjkbertrand/Documents/projects/nextpiper/debug/centroids_noHMM2/homolog_prospection/region_separation/input_probes"
    )
    probe_dir = Path(
        "/home/yjkbertrand/Documents/projects/nextpiper/debug/centroids_noHMM2/bug_instances/probe"
    )

    scaffolds_dir = Path(
        "/home/yjkbertrand/Documents/projects/nextpiper/debug/centroids_noHMM2/homolog_prospection/region_separation/input_scfs"
    )

    scaffolds_dir = Path(
        "/home/yjkbertrand/Documents/projects/nextpiper/debug/centroids_noHMM2/bug_instances/scaffolds"
    )
    out_dir = Path(
        "/home/yjkbertrand/Documents/projects/nextpiper/debug/centroids_noHMM2/homolog_prospection/test"
    )
    out_dir = Path(
        "/home/yjkbertrand/Documents/projects/nextpiper/debug/centroids_noHMM2/bug_instances/out_dir"
    )
    parameters = [8, 0.85, 0.1, 10, 0.7, "TIUZ_probe4471"]
    parameters = [8, 0.85, 0.1, 10, 0.7, "HLJG_probe5220"]
    for scfs in scaffolds_dir.glob("*.fasta"):
        # if not scfs.name == "4471.fasta":
        #     continue
        probes_name = f"probes_{scfs.name.split('_')[1]}"
        probes = probe_dir / probes_name
        print(f"{scfs=},  {probes=}")
        olc = OverlappingCds(str(probes), str(scfs), *parameters)
        print("overlapping:", olc)
        matrix = "/home/yjkbertrand/Documents/projects/nextpiper/test_data/test_paralogy_2/blosum62.csv"
        olc.paralogy_search(matrix)
        print("saving")
        olc.save_records(out_dir)
        break

    # scfs = "/home/yjkbertrand/Documents/projects/nextpiper/debug/5899_test.fasta"
    # probes = probe_dir / "5899.fasta"
    # olc = OverlappingCds(str(probes), str(scfs), *parameters)
    # matrix = "/home/yjkbertrand/Documents/projects/nextpiper/test_data/test_paralogy_2/blosum62.csv"
    # olc.paralogy_search(matrix)


if __name__ == "__main__":
    if "snakemake" in globals():
        snakemake_call(snakemake)
    else:
        main()
