
# Update default config with runtime config
configfile: os.path.join(workflow.basedir, "../", "config", "config.yaml")
configfile: os.path.join(workflow.basedir, "../", "config", "system_config.yaml")
config.update(config["nextpiper"]) # convenience if using namespaced config


# Rules files
include: os.path.join(workflow.basedir, "rules", "common.smk")
include: os.path.join(workflow.basedir, "rules", "preflight.smk")

## List of outputs
targets = []


include: os.path.join(workflow.basedir, "rules", "0_reads_preprocessing", "0.1_trimming.smk")
include: os.path.join(workflow.basedir, "rules", "1_mapping", "1.1_mapping_bwa_mem2.smk")
include: os.path.join(workflow.basedir, "rules", "1_mapping", "1.2_read_distribution.smk")
include: os.path.join(workflow.basedir, "rules", "2_probes_translation", "2.1_transdecoder.smk")
include: os.path.join(workflow.basedir, "rules", "3_homologs_assembly", "3.1_assembly_spades.smk")
include: os.path.join(workflow.basedir, "rules", "3_homologs_assembly", "3.2_prefix_assemblies.smk")
include: os.path.join(workflow.basedir, "rules", "4_clustering", "4.1_cross_sample_merging.smk")

# Target rules
@targetRule
rule all:
    input:
        targets,

@targetRule
rule print_targets:
    run:
        print("\nTop level rules are: \n", file=sys.stderr)
        print("* " + "\n* ".join(target_rules) + "\n\n", file=sys.stderr)
