
# Update default config with runtime config
configfile: os.path.join(workflow.basedir, "../", "config", "config.yaml")
configfile: os.path.join(workflow.basedir, "../", "config", "system_config.yaml")
config.update(config["nextpiper"]) # convenience if using namespaced config


# Rules files
include: os.path.join(workflow.basedir, "rules", "common.smk")
include: os.path.join(workflow.basedir, "rules", "preflight.smk")

## List of outputs
targets = []


include: os.path.join(workflow.basedir, "rules", "0_reads_preprocessing", "0.1_trimming.smk")


# Target rules
@targetRule
rule all:
    input:
        targets,

@targetRule
rule print_targets:
    run:
        print("\nTop level rules are: \n", file=sys.stderr)
        print("* " + "\n* ".join(target_rules) + "\n\n", file=sys.stderr)
