# Namespaced config file example
nextpyper:
    args: # Command line args will be (over)written here at runtime
        input:
        output:
        probe_pattern: (\d{4})$
        multi_probes:
    # Add customisable config here
    pipeline:
        preprocessing:
            trim_qual: 30
            min_len: 75
        probes_translation:
            translated_prop: 0.95
            stop_per_1Kbp: 2 
            min_exon_length: 20
        cp_cleaning:
            min_sp_probes_cov: 80
        multi_probe_clustering:
            mmseq2_min_seq_id: 0.8
        spades:
            k: auto
        scaffolds_extension:
            exploration:
                floor_len_extension: 3000
                ceiling_len_extension: 6000
                probe_len_scaling: 3
                max_intron_size: auto
            output:
                max_extensions: 5
        seeds:
            min_sister_sample_freq: 0.5
        saute:
            heuristic:
                primary_target_depth: 15
                secondary_target_depth: 30
                k1_min: 0.3
                k1_max: 0.5
                k2_min: 0.15
                k2_max: 0.2
            assembly:
                target_cov: 0.2
        mmseqs_matching:
            fields: query,evalue,qstart,qend,qlen,tstart,tend,tlen,theader,gapopen,nident,mismatch
            evalue: 1.000E-6
            min_orf_len: 15
            sensitivity: 7.5
        homolog_filtering:
            seeds_scf_min_cov: 0.0
            seeds_scf_min_idt: 0.6
            homolog_scf_min_cov: 0.1
            homolog_scf_min_idt: 0.6
        divergence_estimation:
            min_cov: 0.5
            flatenning_prop: 0.1
        region_separation:
            min_fragment_cov: 0.1
            min_exonic_length: 10