# Namespaced config file example
nextpyper:
    args: # Command line args will be (over)written here at runtime
        input:
        output:
        probe_pattern: (\d{4})$
        multi_probes:
        graph_simplification: false
        taper_params: 
        trimal_gt:
    # Add customisable config here
    pipeline:
        multi_probe_clustering:
            mmseq2_min_seq_id: 0.8