# Update default config with runtime config
configfile: Path(workflow.basedir) / "../config/config.yaml"
configfile: Path(workflow.basedir) / "../config/system_config.yaml"


config.update(config["nextpyper"])  # convenience if using namespaced config


# Rules files
include: Path(workflow.basedir) / "rules" / "common.smk"
include: Path(workflow.basedir) / "rules/0_preprocessing/0.1_reads.smk"
include: Path(workflow.basedir) / "rules/0_preprocessing/0.2_probes.smk"
include: Path(workflow.basedir) / "rules/1_seeds_assembly/1.1_assembly_spades.smk"
include: Path(workflow.basedir) / "rules/1_seeds_assembly/1.2_seeds_extension.smk"
include: Path(workflow.basedir) / "rules/1_seeds_assembly/1.3_seeds_filtering.smk"
include: Path(workflow.basedir) / "rules/1_seeds_assembly/1.4_seeds_clustering.smk"
include: Path(workflow.basedir) / "rules/2_homologs_assembly/2.1_saute_assembly.smk"
include: Path(workflow.basedir) / "rules/3_homolog_prospection/3.1_allele_collapsing.smk"
include: Path(workflow.basedir) / "rules/3_homolog_prospection/3.2_homologs_filtering.smk"
include: Path(workflow.basedir) / "rules/3_homolog_prospection/3.3_region_separation.smk"


## List of outputs
targets = []

targets.append(
    expand(
        outdir / "homolog_prospection/region_separation/alns/{probes}",
        probes=probes_list,
    )
)
targets.append(
    expand(
        outdir
        / "homolog_prospection/region_separation/consolidated/coverage/{kind}/{sample}.metabat",
        sample=sample_list,
        kind=("exons", "genetigs", "supercontigs"),
    )
)


# Target rules
rule all:
    input:
        targets,


onsuccess:
    print("Workflow finished, without error")
    shell(f"cp {{log}} {outdir/ 'workflow.log'}")


onerror:
    print("An error occurred")
    shell(f"cp {{log}} {outdir/ 'workflow.log'}")
