---
title: "Output structure"
guide-section: "Output"
---

# Output

## Output structure

NextPyper organizes its main outputs in the following fashion:

- Homologous sequences per sample: `<outdir>/outputs/seqs_per_sample`
- Homologous sequences per locus: `<outdir>/outputs/seqs_per_locus`
- Loci Multiple Sequence Alignments (MSAs): `<outdir>/outputs/alignments`

NextPyper output directory follows the following structure:

```
outdir
├── config.yaml      # Final config with parameters used to run the workflow.
├── execution.log    # Snakemake execution log of all workflow jobs.
├── logs/            # Logs generated by the workflow jobs.
├── nextpyper.log    # Summary of params and snakemake invocation.
├── outputs/         # Final outputs of the workflow.
└── workflow/        # Working folder for all the jobs and stages of the pipeline. It contains intermediate and final files.
```

## Sequence versions

The main output of NextPyper are the samples' homologous sequences for each targeted locus. We generate 3 versions of these sequences, depending on the final postprocessing:

- **Exons**: includes only the exonic part of the sequence.
- **Genetigs**: includes exons and introns.
- **Supercontigs**: The full sequence, including exons, introns and flanking regions. 

The exons are the shorter and more conserved version of the output sequences, while the supercontigs are longer and include all discovered variation (which can be a bit noisy). Genetigs usually provide a good balance, containing more signal than the exons without it being overwhelming. You may want to explore which type of sequence suits better your purposes.

## Naming conventions

### Output files

For both `seqs_per_locus` and `alignments` folders, you will find the sequences organized per locus, in separate folders, following the naming convention: `<LocusID>_<frag_start>_<frag_end>_<seq_version>.fasta`, where: 

- **LocusID**: identifier for the Locus.
- **frag_start**: Start position of the sequence (relative to the probe).
- **frag_start**: End position of the sequence (relative to the probe).
- **seq_version**: Either exons, genetigs, or supercontigs versions of the sequences.

For instance, a part of an output directory can look like this:

```{.default}
outdir/outputs/seqs_per_locus
├── 4793
│   ├── 4793_18_540_exons.fasta
│   ├── 4793_18_540_genetigs.fasta
│   └── 4793_18_540_supercontigs.fasta
└── 4796
    ├── 4796_0_158_exons.fasta
    ├── 4796_0_158_genetigs.fasta
    ├── 4796_0_158_supercontigs.fasta
    ├── 4796_179_237_exons.fasta
    ├── 4796_179_237_genetigs.fasta
    └── 4796_179_237_supercontigs.fasta
```

Here, we have 2 loci (`LocusID=4793`, and `LocusID=4796`), where the first one recovered a single long fragment, whereas the second one was recovered in two shorter fragments. 

### Sequence headers

`NextPyper` final sequence headers contain plenty metadata about the sequence. First of all, inspired by Captus, several fields are added to the header after the sequenceID in brackets (`[]`). Those fields are the following:

- **query**: sequenceID of the *probe* that match this sequence. 
- **cover**: How much the sequence covers the probe.
- **ident**: identity relative to the probe.
- **score**: miniprot match score of the sequence to the probe.
- **tribble**: Whether the sequence stems from a tribble. It can be `positive` or `negative`.
- **length**: *Actual* length of the sequence.

In addition to it, each sequenceID is comprised of multiple extra fields following the convention:

`'^(?P<sample1>.*?)\|(?P<sample2>.*?)-(?P<probe>.*?)_EDGE_(?P<seed_id>\d+)_length_(?P<len>\d+)_cov_(?P<cov>[\w.]+):(?P<comp>\d+):(?P<ctg1>\d+):(?P<ctg2>\d+):(?P<kmers>\d+)$'`


For example:

`Echinops_strigosus_ERR5033325|Echinops_strigosus_ERR5033325-4889_EDGE_206_length_1263_cov_34.0863:1:7:7:43051 [query=QXWF_probe4889] [cover=0.48] [ident=0.8864] [score=416] [tribble=negative] [length=1263]`


